### ISSUE TITLE
Annotation 구성 설계

### ISSUE THREAD

**Issue by softpeanut** [Team-ComIT/SimTong-Backend#10]
### Describe

- [x] @UseCase
- [x] @ReadOnlyUseCase
- [x] @DomainService
- [x] @Aggregate
- [x] ComponentScan
- [x] TransactionAspect

### Additional

- UseCase와 ReadOnlyUseCase를 분리한 이유는 스냅샷 생성을 막아 성능 향상을 위함
- UseCase와 ReadOnlyUseCase는 ComponentScan을 통해 Bean으로 등록함
- AOP를 사용한 TransactionAspect를 구현해 응용 서비스 단위로 Transaction을 검

**Comment by softpeanut** [comment]
@khcho0125 좋은 가독성을 위해 @ApplicationService와 @ReadOnlyApplicationService를 각각 @UseCase, @ReadOnlyUseCase로 바꾸면 좋을 것 같은데 어떻게 생각하시나요?

**Comment by khcho0125** [comment]
> @khcho0125 좋은 가독성을 위해 @ApplicationService와 @ReadOnlyApplicationService를 각각 @usecase, @ReadOnlyUseCase로 바꾸면 좋을 것 같은데 어떻게 생각하시나요?

좋은 생각입니다 👍🏻
