### ISSUE TITLE
매개변수 제거 - File Name

### ISSUE THREAD

**Issue by khcho0125** [Team-ComIT/SimTong-Backend#134]
## AS-IS
- AwsS3Adapter inputS3 fileName 필요없는 매개변수

## TO-BE
- 매개변수 변경
- file, fileName → file 
 <img width=600 src="https://user-images.githubusercontent.com/82090641/197561249-33438b03-69b7-47e2-a839-7f3dfc93fe42.jpeg">

**Comment by softpeanut** [comment]
AS-IS와 TO-BE를 보고 무엇을 위한 것인지 잘 파악이 되지 않아요
조금 더 자세하게 적어주시면 좋을 것 같아요 😃

**Comment by khcho0125** [comment]
> AS-IS와 TO-BE를 보고 무엇을 위한 것인지 잘 파악이 되지 않아요
> 
> 조금 더 자세하게 적어주시면 좋을 것 같아요 😃

모바일로 적어서... 수정하겠습니다 😁
