### ISSUE TITLE
SonarCloud 설정 추가

### ISSUE THREAD

**Issue by softpeanut** [Team-ComIT/SimTong-Backend#16]
### Describe

- [x] Team-ComIT/SimTong-Backend 리포지터리 SonarCloud에 추가
- [ ] Secrets에 SONAR_TOKEN 추가
- [ ] build.yml에 sonarcloud 설정 추가
- [ ] .sonarcloud.properties
- [x] Automatical Analysis

### Additional

- Github Action을 이용해 SonarCloud 적용

**Comment by khcho0125** [comment]
yml로 해야하는 건가요 properties로 해야하는 건가요

**Comment by softpeanut** [comment]
@khcho0125 찾아보니까 sonarcloud는 별도 설정 필요없이 github app만 설치해주면 되어서 해당 issue는 close 하겠습니다
