### ISSUE TITLE
User 설계 오류 수정

### ISSUE THREAD

**Issue by khcho0125** [Team-ComIT/SimTong-Backend#28]
### Describe

- [x] User Entity의 UUID에 관한 문제
- [x] UserJpaEntity
- [x] UserMapper

### Additional

현재 발생한 UUID 문제는 DateBase에 저장되어있는 UUID 객체를 다시 DataBase에 저장하려 했을  때
BaseEntity로 인해 UUID가 또 생성되어 기존의 객체를 변경하지 못하고 새로운 객체를 저장하는 문제입니다.

---

- UserEntity의 adminCode Null 허용

- #27 가 병합된 후 해결

**Comment by softpeanut** [comment]
그러면 이 문제는 pk는 각각의 Entity에서 생성하거나 @SuperBuilder를 사용하는 게 어떤가요

**Comment by khcho0125** [comment]
> 그러면 이 문제는 pk는 각각의 Entity에서 생성하거나 @SuperBuilder를 사용하는 게 어떤가요

이 문제가 해결될지는 모르지만 일단 수정해볼 때 알아보겠습니다.
