### ISSUE TITLE
코드 주석 논의 및 주석 정리

### ISSUE THREAD

**Issue by khcho0125** [Team-ComIT/SimTong-Backend#29]
### Describe

- [x] @khcho0125 주석 스타일 변경
- [x] Javadoc 정의에 관해 토의

### Additional

- Live Template 변경 발생

**Comment by khcho0125** [comment]
Javadoc의 version이 각 칸마다 어느 상황에 변경해야 하는지 정확하게 알고 싶습니다.
(프로젝트 버전).(기능 추가).(버그 수정) 으로 알고 있습니다

**Comment by khcho0125** [comment]
그리고 이미 다른 이가 작성한 파일에 변경 사항이 생겼다면 javadoc에 자신 author 추가해도 될까요?

**Comment by softpeanut** [comment]
> 

LGTM 👍

**Comment by softpeanut** [comment]
> @softpeanut Javadoc의 version이 각 칸마다 어느 상황에 변경해야 하는지 정확하게 알고 싶습니다. (프로젝트 버전).(기능 추가).(버그 수정) 으로 알고 있습니다.
> 
> 제가 알고 있는 대로라면 변경사항이 생길 때마다 버전 업을 시켜줘야 하는 건가요?

version의 의미는 각 docs별 버전이 아니라 어떠한 기능이 추가되었을 때 변경사항이 발생하는 모든 docs에 버전을 적용하는 것이라고 생각합니다. 예를 들어서 로그인 기능을 추가하였다면 WebUserAdapter의 버전 증가, UserUseCase의 버전 증가, WebUserLoginRequest의 버전(증가된 버전) 설정 등 해당 기능과 관련된 모든 docs의 버전을 동일하게 적용합니다.

**Comment by khcho0125** [comment]
> > @softpeanut Javadoc의 version이 각 칸마다 어느 상황에 변경해야 하는지 정확하게 알고 싶습니다. (프로젝트 버전).(기능 추가).(버그 수정) 으로 알고 있습니다.
> > 제가 알고 있는 대로라면 변경사항이 생길 때마다 버전 업을 시켜줘야 하는 건가요?
> 
> version의 의미는 각 docs별 버전이 아니라 어떠한 기능이 추가되었을 때 변경사항이 발생하는 모든 docs에 버전을 적용하는 것이라고 생각합니다. 예를 들어서 로그인 기능을 추가하였다면 WebUserAdapter의 버전 증가, UserUseCase의 버전 증가, WebUserLoginRequest의 버전(증가된 버전) 설정 등 해당 기능과 관련된 모든 docs의 버전을 동일하게 적용합니다.

그렇다면 현재는 버전에 신경을 안 써도 되는 것이네요..

**Comment by softpeanut** [comment]
그렇다고 할 수 있죠. 최소 기능이 완성된 후 버전을 신경쓰셔도 될 것 같아요.
