### ISSUE TITLE
User & Spot 연관관계 세팅

### ISSUE THREAD

**Issue by khcho0125** [Team-ComIT/SimTong-Backend#64]
## Describe
- User와 Spot 연관관계 맺기
- User & Spot 쿼리 설계

## Additional
*No Response*

**Comment by softpeanut** [comment]
User - Spot 외에 User - Team 연관관계도 함께 작업하면 좋을 것 같아요

**Comment by khcho0125** [comment]
> User - Spot 외에 User - Team 연관관계도 함께 작업하면 좋을 것 같아요

작업을 하다 보니 수정되는 파일과 생성한 파일이 적지 않아 무리라고 판단됩니다...
