### ISSUE TITLE
NoSQL 모델 설계

### ISSUE THREAD

**Issue by softpeanut** [Team-ComIT/SimTong-Backend#7]
### Describe

- [x] tbl_auth_code <img width="790" alt="image" src="https://user-images.githubusercontent.com/82090641/187159482-fc98e6a0-e84d-4263-b1e4-8612ba814411.png">

- [x] tbl_auth_code_policy <img width="750" alt="image" src="https://user-images.githubusercontent.com/82090641/187159562-0c528644-c58b-47c1-bc1a-ccd889dbcb61.png">

### Additional

- [x] Redis 이용

**Comment by softpeanut** [comment]
@khcho0125 Refresh Token에 관한 설계가 아직 이루어지지 않은 것 같습니다.
회의는 언제가 좋을까요?

**Comment by khcho0125** [comment]
> 것 같습니다.
> 회의는 언제가 좋을까요?

@softpeanut  오늘 저녁에 하실 수 있나요?
